# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-15 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disiplin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kehadiran', models.CharField(blank=True, max_length=100, null=True)),
                ('nilai', models.IntegerField(default=0)),
                ('pelanggaran', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Disiplin',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Kesehatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jasmani', models.CharField(max_length=100)),
                ('nilai', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'jasmani',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pekerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(blank=True, max_length=20, null=True)),
                ('nama_ptp', models.CharField(blank=True, max_length=100, null=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_lahir', models.DateTimeField()),
                ('alamat', models.TextField(blank=True, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('PR', 'Pria'), ('WN', 'Wanita')], default='PR', max_length=2)),
                ('agama', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pekerja',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Petadua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teori', models.CharField(max_length=50)),
                ('praktek', models.CharField(max_length=50)),
                ('nilai', models.IntegerField(default=0)),
                ('pekerja', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Petaduas', to='orm.Pekerja')),
            ],
            options={
                'db_table': 'teori',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=100)),
                ('nilai', models.IntegerField(default=0)),
                ('pekerja', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pkos', to='orm.Pekerja')),
            ],
            options={
                'db_table': 'pko',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Psikotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intelegensi', models.CharField(max_length=100)),
                ('kepribadian', models.CharField(max_length=50)),
                ('nilai', models.IntegerField(default=0)),
                ('pekerja', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Psikotess', to='orm.Pekerja')),
            ],
            options={
                'db_table': 'intelegensi',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='kesehatan',
            name='pekerja',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kesehatans', to='orm.Pekerja'),
        ),
        migrations.AddField(
            model_name='disiplin',
            name='pekerja',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Displins', to='orm.Pekerja'),
        ),
    ]
