# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-15 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_auto_20181115_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pekerja',
            name='status',
            field=models.CharField(choices=[('KW', 'Kawin'), ('BKW', 'Belum Kawin')], default='KW', max_length=2),
        ),
    ]
