# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-15 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_auto_20181115_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pekerja',
            name='nip',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
