# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-15 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_auto_20181115_1643'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pekerja',
            table='Pekerja',
        ),
    ]
