# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-15 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0005_auto_20181115_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pekerja',
            name='nip',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
