# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-15 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0006_auto_20181115_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pekerja',
            name='status',
            field=models.CharField(choices=[('KW', 'Kawin'), ('BK', 'Belum Kawin')], default='KW', max_length=2),
        ),
    ]
