# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-15 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0007_auto_20181115_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disiplin',
            name='kehadiran',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='disiplin',
            name='pelanggaran',
            field=models.IntegerField(default=0),
        ),
    ]
