# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-20 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0009_auto_20181115_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disiplin',
            name='pekerja',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Disiplins', to='orm.Pekerja'),
        ),
    ]
