# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-04 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0011_auto_20181204_0406'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='petadua',
            table='Petadua',
        ),
        migrations.AlterModelTable(
            name='pko',
            table='Pko',
        ),
        migrations.AlterModelTable(
            name='psikotes',
            table='Psikotes',
        ),
    ]
