# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-04 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0012_auto_20181204_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petadua',
            name='praktek',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='petadua',
            name='teori',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='psikotes',
            name='intelegensi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='psikotes',
            name='kepribadian',
            field=models.IntegerField(default=0),
        ),
    ]
