# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-04 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0013_auto_20181204_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pekerja',
            name='nip',
            field=models.IntegerField(default=0),
        ),
    ]
