# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-06 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0014_auto_20181204_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kesehatan',
            name='status_kes',
            field=models.CharField(choices=[('Sehat', 'Sehat'), ('Tidak Sehat', 'Tidak Sehat')], default='Sehat', max_length=15),
        ),
        migrations.AlterField(
            model_name='pekerja',
            name='jenis_kelamin',
            field=models.CharField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita')], default='Pria', max_length=8),
        ),
        migrations.AlterField(
            model_name='pekerja',
            name='status',
            field=models.CharField(choices=[('Kawin', 'Kawin'), ('Belum Kawin', 'Belum Kawin')], default='Kawin', max_length=15),
        ),
    ]
