# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-13 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0015_auto_20181206_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kesehatan',
            old_name='status_kes',
            new_name='status',
        ),
    ]
