# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-13 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0016_auto_20181213_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kesehatan',
            old_name='status',
            new_name='status_kes',
        ),
    ]
