# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-19 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0017_auto_20181213_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='pekerja',
            name='gambar',
            field=models.ImageField(blank=True, help_text='Upload Foto Soal Anda', null=True, upload_to='pekerja'),
        ),
    ]
