# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-23 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0019_pekerja_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bobot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pko', models.IntegerField(default=0)),
                ('disiplin', models.IntegerField(default=0)),
                ('kesehatan', models.IntegerField(default=0)),
                ('psikotes', models.IntegerField(default=0)),
                ('petadua', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Bobot',
                'ordering': ['id'],
            },
        ),
    ]
