# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-03 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0020_bobot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bobot',
        ),
    ]
