# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-04 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0022_pemilih'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pemilih',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='pemilih',
            table='Pemilih',
        ),
    ]
