# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-08 13:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orm', '0023_auto_20190104_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='HakAkses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Login',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='pekerja',
            name='user',
        ),
    ]
