# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-08 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import orm.FileUploader


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0024_auto_20190108_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pekerja',
            name='gambar',
        ),
        migrations.AddField(
            model_name='pekerja',
            name='picture',
            field=models.ImageField(blank=True, default='pekerja/icon.png', help_text='Upload Fotomu sebagai gambar profile', null=True, upload_to=orm.FileUploader.file_profile),
        ),
    ]
