# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-10 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import orm.FileUploader


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0025_auto_20190108_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.IntegerField(default=0)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_ptp', models.CharField(blank=True, max_length=100, null=True)),
                ('visi', models.CharField(blank=True, max_length=100, null=True)),
                ('misi', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, default='calon/icon.png', help_text='Upload Fotomu sebagai gambar profile', null=True, upload_to=orm.FileUploader.file_profile)),
            ],
            options={
                'db_table': 'Calon',
                'ordering': ['id'],
            },
        ),
    ]
