# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-10 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import orm.FileUploader


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0026_calon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemilih',
            name='picture',
            field=models.ImageField(blank=True, default='calon/icon.png', help_text='Upload Fotomu sebagai gambar profile', null=True, upload_to=orm.FileUploader.file_profile),
        ),
    ]
