# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-11 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import orm.FileUploader


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0028_auto_20190110_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calon',
            old_name='nama',
            new_name='nama_ketua',
        ),
        migrations.AddField(
            model_name='calon',
            name='nama_wakil',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calon',
            name='picture',
            field=models.ImageField(blank=True, default='calon/icon.png', help_text='Upload Fotomu sebagai gambar profile', null=True, upload_to=orm.FileUploader.file_calon),
        ),
        migrations.AlterField(
            model_name='pemilih',
            name='picture',
            field=models.ImageField(blank=True, default='pemilih/icon.png', help_text='Upload Fotomu sebagai gambar profile', null=True, upload_to=orm.FileUploader.file_pemilih),
        ),
    ]
