# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-11 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0029_auto_20190111_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calon',
            name='nama_ptp',
        ),
        migrations.RemoveField(
            model_name='calon',
            name='nip',
        ),
    ]
