# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-13 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0032_auto_20190111_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='calon',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
