# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-18 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0033_calon_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calon',
            old_name='nama_ketua',
            new_name='nama_calon',
        ),
        migrations.RemoveField(
            model_name='calon',
            name='nama_wakil',
        ),
        migrations.RemoveField(
            model_name='calon',
            name='picture2',
        ),
    ]
